version: '3.8'
services:

  ml-data-api:
    build: .
    container_name: ml-data-api
    restart: always
    ports:
      - 50051:50051
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=

  minio-db:
    image: minio/minio
    container_name: minio-db
    restart: always
    ports:
      - 9000:9000
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: root1234
    volumes:
      - ./data/minIO/:/data
    command: server /data