# Documentation: https://hydra.cc/docs/1.3/intro/

defaults:  
  - _self_
  - preset: IATA_set1 
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled
  
hydra:
  output_subdir: null  
  run:  
    dir: .


cwd: ${hydra:runtime.cwd}

# path to data directory
output_data_dir: ${cwd}/data/scraped/
available_airports: ${cwd}/configs/scraper/available_codes.json

force_scraping: False
headless: True
num_workers: 2