defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .


cwd: ${hydra:runtime.cwd}
secure_connection: False
model_dir: ${cwd}/out/