# Documentation: https://hydra.cc/docs/1.3/intro/

defaults:  
  - _self_
  - preset: IATA_set1
  
hydra:
  output_subdir: null  
  run:
    dir: .


cwd: ${hydra:runtime.cwd}

# path to data directory
output_data_dir: ${cwd}/data/scraped/
available_airports: ${cwd}/configs/scrape/available_codes.json

force_scraping: True
headless: True
num_workers: 5

minio:
  endpoint: ${oc.env:MINIO_ENDPOINT}
  bucket_name_training: ${oc.env:MINIO_BUCKET_NAME_TRAINING}
  access_key: ${oc.env:MINIO_ACCESS_KEY}
  secret_key: ${oc.env:MINIO_SECRET_KEY}
  secure_connection: False