# Documentation: https://hydra.cc/docs/1.3/intro/

defaults:  
  - _self_
  - preset: IATA_set1 
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled
  
hydra:
  output_subdir: null  
  run:  
    dir: .

# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# you can replace it with "." if you want the root to be the current working directory
root_dir: ${oc.env:PROJECT_ROOT}

# path to data directory
output_data_dir: ${root_dir}/data/scraped/

available_airports: ${root_dir}/scraper_configs/available_codes.json

run_once: False
headless: False
num_workers: 2