defaults:
  - _self_

hydra:
  output_subdir: null
  run:
    dir: .

cwd: ${hydra:runtime.cwd}

train_data_dir: ${cwd}/data/scraped/
model_out_dir: ${cwd}/out/

date_format: "%Y-%m-%d"

force_training: True

minio:
  endpoint: ${oc.env:MINIO_ENDPOINT}
  bucket_name_training: ${oc.env:MINIO_BUCKET_NAME_TRAINING}
  bucket_name_model: ${oc.env:MINIO_BUCKET_NAME_MODEL}
  access_key: ${oc.env:MINIO_ACCESS_KEY}
  secret_key: ${oc.env:MINIO_SECRET_KEY}
  secure_connection: False

train_params:
  {
    "boosting_type": "gbdt",
    "objective": "regression",
    "metric": ["l2", "l1"],
    "num_leaves": 31,
    "learning_rate": 0.05,
    "feature_fraction": 0.9,
    "bagging_fraction": 0.8,
    "bagging_freq": 5,
    "verbose": 0,
  }
